### ISSUE TITLE
Aimeos\Aimeos\Custom\Composer::install throws php error

### ISSUE THREAD

**Issue by web-commerce-og** [aimeos/aimeos-typo3#119]
using "aimeos/aimeos-typo3": "19.10.6" on TYPO3 eLTS 8.7.34 and php 7.2 on windows ddev

running the post install script 
```
"post-install-cmd": [
      "Aimeos\\Aimeos\\Custom\\Composer::install"
    ],
```
produces the following error:

```
> Aimeos\Aimeos\Custom\Composer::install
Installing Aimeos public files from HTML client
Creating symlink to Aimeos extension directory
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Aimeos\Aimeos\Custom\Composer::join() must be an instance of Aimeos\Aimeos\Custom\Event, instance of Composer\Script\Event given, called in /var/www/html/web/typo3conf/ext/aimeos/Classes/Custom/Composer.php on line 53 and defined in /var/www/html/web/typo3conf/ext/aimeos/Classes/Custom/Composer.php:146
Stack trace:
#0 /var/www/html/web/typo3conf/ext/aimeos/Classes/Custom/Composer.php(53): Aimeos\Aimeos\Custom\Composer::join(Object(Composer\Script\Event)) #1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Aimeos\Aimeos\Custom\Composer::install(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Aimeos\\Aimeos\\C...', 'install', Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Objec in /var/www/html/web/typo3conf/ext/aimeos/Classes/Custom/Composer.php on line 146
```

attached patch fixes the problem for me. 
[fix_aimeos_composer.zip](https://github.com/aimeos/aimeos-typo3/files/4723006/fix_aimeos_composer.zip)

**Comment by aimeos** [comment]
Thank you, it's already fixed in the 2019.10 branch. Use

`composer req aimeos/aimeos-typo3:2019.10.x-dev`

until the new version has been tagged.
