### ISSUE TITLE
Uncaught TYPO3 Exception on first install (TER)

### ISSUE THREAD

**Issue by stephankellermayr** [aimeos/aimeos-typo3#152]
There's a problem with the latest release (20.10.3):
If you install this extension the first time, the following error occurs:
```
Aimeos\MW\DB\Exception thrown in file /typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php in line 75.
Requested URL: https://###URL###/typo3/index.php?route=%2Fajax%2Fsystem-information%2Frender&token=--AnonymizedToken--&skipSessionUpdate=1 - {
	"TYPO3_MODE":"BE",
	"exception":"Aimeos\\MW\\DB\\Exception: SQLSTATE[42S02]:
		Base table or view not found: 1146 Table '###DATABASE_NAME###.mshop_locale_site' doesn't exist: SELECT \"siteid\", \"label\", \"nleft\", \"nright\" FROM \"mshop_locale_site\" ORDER BY \"nleft\"
		in /typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php:75
	Stack trace:
	#0 /typo3conf/ext/aimeos/Configuration/TCA/Overrides/be_users.php(14): Aimeos\\MW\\DB\\Statement\\DBAL\\Simple->execute()
	#1 /typo3conf/ext/aimeos/Configuration/TCA/Overrides/be_users.php(56): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::{closure}()
	#2 /typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1708): require('/var/www/client...')
	#3 /typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1658): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::buildBaseTcaFromSingleFiles()
	#4 /typo3/sysext/core/Classes/Core/Bootstrap.php(518): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::loadBaseTca()
	#5 /typo3/sysext/core/Classes/Core/Bootstrap.php(163): TYPO3\\CMS\\Core\\Core\\Bootstrap::loadBaseTca()
	#6 /typo3/index.php(25): TYPO3\\CMS\\Core\\Core\\Bootstrap::init()
	#7 /typo3/index.php(26): {closure}()
	#8 {main}"
}
```

It seems that the table `mshop_locale_site` in `Configuration/TCA/Overrides/be_users.php` is queried before it has been created.

**Comment by stephankellermayr** [comment]
Solved with #153  ...thanks for the quick reply!
